In [1]:
import pandas as pd
# 讀csv儅
df = pd.read_csv("Total Bond Market ETF List (82).csv",index_col='Symbol')

In [2]:
# 看前5筆數據
df.head()

,ETF Name,Asset Class,Total Assets,YTD,Avg Volume,Previous Closing Price,1-Day Change,Inverse,Leveraged,1 Week,...,Returns Rating,Volatility Rating,Dividend Rating,Concentration Rating,ESG Score,ESG Score Peer Percentile (%),ESG Score Global Percentile (%),Carbon Intensity (Tons of CO2e / $M Sales),SRI Exclusion Criteria (%),Sustainable Impact Solutions (%)
Symbol,,,,,,,,,,,,,,,,,,,,,
AGG,iShares Core U.S. Aggregate Bond ETF,Bond,"$57,071,132,686.00",0.45%,"6,141,948",$106.97,-0.46%,No,No,0.27%,...,A-,A-,B+,A,6.14,73.97%,71.15%,333.04,3.38%,1.05%
BND,Vanguard Total Bond Market ETF,Bond,"$36,982,657,772.00",0.83%,"2,943,894",$79.67,-0.52%,No,No,0.52%,...,A-,B+,B+,A+,6.13,71.92%,70.97%,355.94,3.84%,1.22%
BSV,Vanguard Short-Term Bond ETF,Bond,"$23,944,569,102.00",0.42%,"3,493,945",$78.74,-0.40%,No,No,0.24%,...,A-,A,C+,A,6.34,82.71%,77.26%,221.62,3.04%,1.27%
BNDX,Vanguard Total International Bond ETF,Bond,"$13,673,292,937.00",0.98%,"1,808,582",$54.73,-0.11%,No,No,0.28%,...,A,B+,C+,NaN,6.26,65.85%,74.99%,150.77,1.90%,0.64%
MINT,PIMCO Enhanced Short Maturity Strategy Fund,Bond,"$11,853,323,153.00",0.23%,"1,462,739",$101.18,-0.22%,No,No,-0.12%,...,A,A-,A,A+,4.89,9.77%,30.15%,262.78,7.51%,1.53%

In [3]:
# 看Inception欄位
df[['Inception']]

         Inception
Symbol
AGG     2003-09-22
BND     2007-04-10
BSV     2007-04-10
BNDX    2013-06-04
MINT    2009-11-16
BIV     2007-04-10
NEAR    2013-09-25
SCHZ    2011-07-14
FTSM    2014-08-05
SPAB    2007-05-23
BLV     2007-04-10
TOTL    2015-02-24
IUSB    2014-06-10
GVI     2007-01-11
ISTB    2012-10-18
BOND    2012-02-29
IAGG    2015-11-10
HTRB    2017-09-27
FBND    2014-10-06
VBND    2014-10-16
FIXD    2017-02-14
AGGY    2015-07-09
RAVI    2012-10-09
ILTB    2009-12-08
LDUR    2014-01-22
FFTI    2017-06-06
PULS    2018-04-05
UITB    2017-10-24
FTSD    2013-11-04
UCON    2018-06-04
...            ...
AFIF    2018-09-18
SHAG    2017-05-18
JMST    2018-10-16
BNDC    2016-11-21
FFIU    2017-08-21
IMFI    2018-12-06
GTO     2016-02-10
JAGG    2018-12-12
JMUB    2018-10-29
OPER    2018-07-11
NUSA    2017-03-31
BYLD    2014-04-22
LSST    2017-12-27
GRNB    2017-03-03
AGND    2013-12-18
WBND    2018-10-03
BGRN    2018-11-13
IMFC    2018-07-25
PBND    2017-09-29
AWTM    2019-01-29
IMFD    2018-12-06
FWDB    2011-06-20
KCNY    2014-12-02
CRUSC   2018-01-09
MCEF    2016-09-27
EVLMC   2016-03-30
WYDE    2014-08-05
FLIA    2018-05-30
SAGG    2011-03-23
GLBY    2018-12-13

[82 rows x 1 columns]

In [4]:
# 去除2015-12-31之後的etf
filtered_df=df[df['Inception']<='2015-12-31']

In [5]:
# 看去除之後的前5筆數據
filtered_df.head()

,ETF Name,Asset Class,Total Assets,YTD,Avg Volume,Previous Closing Price,1-Day Change,Inverse,Leveraged,1 Week,...,Returns Rating,Volatility Rating,Dividend Rating,Concentration Rating,ESG Score,ESG Score Peer Percentile (%),ESG Score Global Percentile (%),Carbon Intensity (Tons of CO2e / $M Sales),SRI Exclusion Criteria (%),Sustainable Impact Solutions (%)
Symbol,,,,,,,,,,,,,,,,,,,,,
AGG,iShares Core U.S. Aggregate Bond ETF,Bond,"$57,071,132,686.00",0.45%,"6,141,948",$106.97,-0.46%,No,No,0.27%,...,A-,A-,B+,A,6.14,73.97%,71.15%,333.04,3.38%,1.05%
BND,Vanguard Total Bond Market ETF,Bond,"$36,982,657,772.00",0.83%,"2,943,894",$79.67,-0.52%,No,No,0.52%,...,A-,B+,B+,A+,6.13,71.92%,70.97%,355.94,3.84%,1.22%
BSV,Vanguard Short-Term Bond ETF,Bond,"$23,944,569,102.00",0.42%,"3,493,945",$78.74,-0.40%,No,No,0.24%,...,A-,A,C+,A,6.34,82.71%,77.26%,221.62,3.04%,1.27%
BNDX,Vanguard Total International Bond ETF,Bond,"$13,673,292,937.00",0.98%,"1,808,582",$54.73,-0.11%,No,No,0.28%,...,A,B+,C+,NaN,6.26,65.85%,74.99%,150.77,1.90%,0.64%
MINT,PIMCO Enhanced Short Maturity Strategy Fund,Bond,"$11,853,323,153.00",0.23%,"1,462,739",$101.18,-0.22%,No,No,-0.12%,...,A,A-,A,A+,4.89,9.77%,30.15%,262.78,7.51%,1.53%

In [6]:
# 得到要抓數據的symbols
etf_symbols = filtered_df.index[:]
etf_symbols

Index(['AGG', 'BND', 'BSV', 'BNDX', 'MINT', 'BIV', 'NEAR', 'SCHZ', 'FTSM',
       'SPAB', 'BLV', 'TOTL', 'IUSB', 'GVI', 'ISTB', 'BOND', 'IAGG', 'FBND',
       'VBND', 'AGGY', 'RAVI', 'ILTB', 'LDUR', 'FTSD', 'ULST', 'FLTB', 'XMPT',
       'FIBR', 'MINC', 'GBF', 'AGZD', 'NFLT', 'HOLD', 'FCOR', 'BYLD', 'AGND',
       'FWDB', 'KCNY', 'WYDE', 'SAGG'],
      dtype='object', name='Symbol')

In [26]:
import requests
import re
import pandas as pd
from io import StringIO
import time

symbol = 'AGG'
#開始與結束時間
start_date = '1451491200'
end_date = '1552924800'
#使用regular expression找到對應的crumble
crumble_link = 'https://finance.yahoo.com/quote/{0}/history?p={0}'
crumble_regex = r'CrumbStore":{"crumb":"(.*?)"}'
cookie_regex = r'set-cookie: (.*?);'

link = crumble_link.format(symbol)
session = requests.Session()
response = session.get(link)

text = str(response.content)
match = re.search(crumble_regex,text)
crumbs = match.group(1)

cookie = session.cookies.get_dict()

url = 'https://query1.finance.yahoo.com/v7/finance/download/{0}?period1={1}&period2={2} \
&interval=1d&events=history&crumb={3}'.format(symbol,start_date,end_date,crumbs)
# 使用requests.get()得到數據
download=requests.get(url,cookies=cookie,timeout=5)
time.sleep(2)
# 讀csv檔案
df = pd.read_csv(StringIO(download.text)).set_index('Date')
# 調整col的名字
df = df[['Adj Close']]
df = df.rename(columns={'Adj Close':symbol})

In [27]:
df.head(20)

                   AGG
Date
2015-12-30   99.345367
2015-12-31   99.612816
2016-01-04   99.575951
2016-01-05   99.622025
2016-01-06  100.000175
2016-01-07   99.990959
2016-01-08  100.212311
2016-01-11   99.926399
2016-01-12  100.147728
2016-01-13  100.378296
2016-01-14  100.341415
2016-01-15  100.461288
2016-01-19  100.359863
2016-01-20  100.442886
2016-01-21  100.304520
2016-01-22  100.378296
2016-01-25  100.322960
2016-01-26  100.452072
2016-01-27  100.470543
2016-01-28  100.553520

In [28]:
# 將symbols中的symbol對於的price都抓下來
for symbol in etf_symbols[1:]:
    link = crumble_link.format(symbol)
    session = requests.Session()
    response = session.get(link)

    text = str(response.content)
    match = re.search(crumble_regex,text)
    crumbs = match.group(1)

    cookie = session.cookies.get_dict()

    url = 'https://query1.finance.yahoo.com/v7/finance/download/{0}?period1={1}&period2={2} \
    &interval=1d&events=history&crumb={3}'.format(symbol,start_date,end_date,crumbs)
    
    try:
        download=requests.get(url,cookies=cookie,timeout=20)
        download.raise_for_status()
        time.sleep(5)

        new_df = pd.read_csv(StringIO(download.text)).set_index('Date')
        new_df = new_df[['Adj Close']]
        new_df = new_df.rename(columns={'Adj Close':symbol})
        df[symbol] = new_df;
    except:
        print(symbol+' failed.')
        pass

BNDX failed.
IAGG failed.
ULST failed.
FLTB failed.
MINC failed.
AGND failed.

In [29]:
# 對於失敗的symbol再抓一次
failed_symbols = ['BNDX','IAGG','ULST','FLTB','MINC','AGND']
for symbol in failed_symbols:
    link = crumble_link.format(symbol)
    session = requests.Session()
    response = session.get(link)

    text = str(response.content)
    match = re.search(crumble_regex,text)
    crumbs = match.group(1)

    cookie = session.cookies.get_dict()

    url = 'https://query1.finance.yahoo.com/v7/finance/download/{0}?period1={1}&period2={2} \
    &interval=1d&events=history&crumb={3}'.format(symbol,start_date,end_date,crumbs)
    
    try:
        download=requests.get(url,cookies=cookie,timeout=20)
        download.raise_for_status()
        time.sleep(5)

        new_df = pd.read_csv(StringIO(download.text)).set_index('Date')
        new_df = new_df[['Adj Close']]
        new_df = new_df.rename(columns={'Adj Close':symbol})
        df[symbol] = new_df;
    except:
        print(symbol+' failed.')
        pass

In [36]:
df.head()

,AGG,BND,BSV,MINT,BIV,NEAR,SCHZ,FTSM,SPAB,BLV,...,FWDB,KCNY,WYDE,SAGG,BNDX,IAGG,ULST,FLTB,MINC,AGND
Date,,,,,,,,,,,,,,,,,,,,,
2015-12-30,99.345367,74.030540,75.365646,95.003563,75.977394,47.550110,47.479706,56.983047,26.094627,76.637024,...,21.923071,32.227638,38.250000,32.573521,49.085400,46.838024,38.045639,46.730671,44.449177,41.170654
2015-12-31,99.612816,74.177483,75.413040,94.984634,76.096497,47.569115,47.599861,56.992565,26.145035,76.956161,...,21.932032,32.129230,38.090000,32.573521,49.169086,46.903488,38.045639,46.777725,44.412453,41.189316
2016-01-04,99.575951,74.140762,75.441475,95.079063,76.243126,47.483524,47.636833,57.021145,26.167957,77.195518,...,21.842405,31.970274,38.713001,32.425407,49.271347,46.987694,38.102856,46.787144,44.403278,41.096062
2016-01-05,99.622025,74.232628,75.431992,95.079063,76.334732,47.550110,47.646095,57.021145,26.177118,77.177803,...,21.932032,31.985418,38.300999,32.464905,49.243462,47.062523,38.112396,46.730671,44.421631,41.096062
2016-01-06,100.000175,74.563278,75.517281,95.088493,76.646225,47.569115,47.784729,57.021145,26.296268,77.798332,...,21.932032,31.764002,38.500000,32.385910,49.429436,47.058784,38.102856,46.655361,44.485901,40.965500

In [37]:
FIBR_url = 'https://www.moneydj.com/ETF/X/xdjbcd/Basic0003BCD.xdjbcd?etfid=FIBR&b=20151231&c=20190319'

In [38]:
download_FIBR = requests.get(FIBR_url)
download_FIBR.status_code

200

In [49]:
str = download_FIBR.text.split(' ')
date = str[0].split(',')
date  = [eachdate[:4]+'-'+eachdate[4:6]+'-'+eachdate[6:] for eachdate in date]
price = str[1].split(',')

In [55]:
df_FIBR = pd.DataFrame(data=price,index=date,columns=['FIBR'])

In [57]:
df_FIBR.head()

               FIBR
2015-12-31  96.6900
2016-01-04  96.6700
2016-01-05  96.7900
2016-01-06  96.9600
2016-01-07  96.9300

In [58]:
df['FIBR'] = df_FIBR;

In [60]:
df.head()

,AGG,BND,BSV,MINT,BIV,NEAR,SCHZ,FTSM,SPAB,BLV,...,FWDB,KCNY,WYDE,SAGG,BNDX,IAGG,ULST,FLTB,MINC,AGND
Date,,,,,,,,,,,,,,,,,,,,,
2015-12-30,99.345367,74.030540,75.365646,95.003563,75.977394,47.550110,47.479706,56.983047,26.094627,76.637024,...,21.923071,32.227638,38.250000,32.573521,49.085400,46.838024,38.045639,46.730671,44.449177,41.170654
2015-12-31,99.612816,74.177483,75.413040,94.984634,76.096497,47.569115,47.599861,56.992565,26.145035,76.956161,...,21.932032,32.129230,38.090000,32.573521,49.169086,46.903488,38.045639,46.777725,44.412453,41.189316
2016-01-04,99.575951,74.140762,75.441475,95.079063,76.243126,47.483524,47.636833,57.021145,26.167957,77.195518,...,21.842405,31.970274,38.713001,32.425407,49.271347,46.987694,38.102856,46.787144,44.403278,41.096062
2016-01-05,99.622025,74.232628,75.431992,95.079063,76.334732,47.550110,47.646095,57.021145,26.177118,77.177803,...,21.932032,31.985418,38.300999,32.464905,49.243462,47.062523,38.112396,46.730671,44.421631,41.096062
2016-01-06,100.000175,74.563278,75.517281,95.088493,76.646225,47.569115,47.784729,57.021145,26.296268,77.798332,...,21.932032,31.764002,38.500000,32.385910,49.429436,47.058784,38.102856,46.655361,44.485901,40.965500

In [65]:
# 將抓到的data存成scv
df.to_csv('crawler_data.csv')